name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.101

      - name: Install iOS workload (clean)
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload list

      - name: Restore
        run: dotnet restore ZdaszToApp/ZdaszToApp.iOS/ZdaszToApp.iOS.csproj

      - name: Publish iOS
        run: dotnet publish -c Release -f net8.0-ios17.0 ZdaszToApp/ZdaszToApp.iOS/ZdaszToApp.iOS.csproj
